version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - mysql-network  
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1      
    networks:
      - mysql-network   
      
networks:
  mysql-network:
    driver: bridge        
   
