
version: '3'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "1234"
    ports:
      - "25672:15672"
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/rabbitmq:/var/lib/rabbitmq
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge  
