version: '3'

services:

  zabbix-db:
    image: mysql:5.7
    volumes:
      - /opt/zabbix/mysql:/var/lib/mysql
    ports:
      - "3306:3306"  
    environment:     
      - MYSQL_ROOT_PASSWORD=secret 
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
    depends_on:
      - zabbix-db
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /opt/zabbix:/etc/localtime:ro
    links:
      - zabbix-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.0-latest
    ports:
      - "8081:80"
      - "8443:443"
    links:
      - zabbix-db
      - zabbix-server
    depends_on:
      - zabbix-db
      - zabbix-server

    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
 
